# Generated by Django 2.2 on 2024-12-20 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('CR', 'Carne Roja'), ('CB', 'Carne Blanca'), ('P', 'Pasta'), ('G', 'Gaseosa'), ('CH', 'Con Alcohol'), ('SG', 'Sin Gas')], max_length=2)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('num_Mesa', models.AutoField(primary_key=True, serialize=False)),
                ('cantSillas', models.IntegerField()),
                ('status', models.CharField(choices=[('LB', 'Libre'), ('RS', 'Reservada'), ('OP', 'Ocupada'), ('NO', 'No Disponible')], default='Libre', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('num_Res', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Buffet.Mesa')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffet.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='Buffet.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
